CREATE TABLE cca01_genero (id_genero int4 NOT NULL, tx_nombre varchar(50) NOT NULL, tx_descripcion varchar(255) NOT NULL, st_activo bool NOT NULL, PRIMARY KEY (id_genero));
CREATE TABLE cca02_rol (id_rol int4 NOT NULL, tx_nombre varchar(50) NOT NULL, tx_descripcion varchar(255) NOT NULL, st_activo bool NOT NULL, PRIMARY KEY (id_rol));
CREATE TABLE cci01_servicio (id_servicio int4 NOT NULL, tx_nombre varchar(50) NOT NULL, tx_descripcion varchar(255) NOT NULL, st_activo int4 NOT NULL, nu_duracion int4 NOT NULL, PRIMARY KEY (id_servicio));
CREATE TABLE tca01_persona (id_persona SERIAL NOT NULL, fk_id_genero int4 NOT NULL, tx_nombre varchar(100) NOT NULL, tx_primer_apellido varchar(100) NOT NULL, tx_segundo_apellido varchar(100), fh_nacimiento date NOT NULL, PRIMARY KEY (id_persona));
CREATE TABLE tca02_usuario (id_usuario int4 NOT NULL, fk_id_rol int4 NOT NULL, tx_login varchar(100) NOT NULL, tx_password varchar(255) NOT NULL, st_activo bool NOT NULL, PRIMARY KEY (id_usuario));
CREATE TABLE tce01_establecimiento (id_establecimiento SERIAL NOT NULL, tx_nombre varchar(100) NOT NULL, PRIMARY KEY (id_establecimiento));
CREATE TABLE tce02_sucursal (id_sucursal SERIAL NOT NULL, fk_id_establecimiento int4 NOT NULL, tx_nombre varchar(100) NOT NULL, gm_ubicacion geometry NOT NULL, PRIMARY KEY (id_sucursal));
CREATE TABLE tce03_empleado (id_empleado int4 NOT NULL, fk_id_sucursal int4 NOT NULL, PRIMARY KEY (id_empleado));
CREATE TABLE tce04_dia_laboral (id_dia SERIAL NOT NULL, tx_nombre varchar(50) NOT NULL, tx_descripcion varchar(255) NOT NULL, st_activo int4 NOT NULL, PRIMARY KEY (id_dia));
CREATE TABLE tce05_dia_descanso (id_dia_descanso SERIAL NOT NULL, fk_id_empleado int4 NOT NULL, fh_descanso date NOT NULL, PRIMARY KEY (id_dia_descanso));
CREATE TABLE tce06_empleado_horario (fk_id_horario int4 NOT NULL, fk_id_persona int4 NOT NULL, PRIMARY KEY (fk_id_horario, fk_id_persona));
CREATE TABLE tce07_bloque_cita (fk_id_sucursal int4 NOT NULL, fk_id_cita int4, fh_inicio timestamp NOT NULL, fh_fin timestamp NOT NULL);
CREATE TABLE tce08_horario (id_horario SERIAL NOT NULL, fk_id_sucursal int4 NOT NULL, fk_id_dia int4 NOT NULL, tm_inicio time NOT NULL, tm_fin time NOT NULL, PRIMARY KEY (id_horario));
CREATE TABLE tci01_estado_lista_precio (id_estado SERIAL NOT NULL, tx_nombre varchar(50) NOT NULL, PRIMARY KEY (id_estado));
CREATE TABLE tci02_servicio_lista_precio (fk_id_servicio int4 NOT NULL, fk_id_lista_precio int4 NOT NULL, nu_precio int4 NOT NULL, PRIMARY KEY (fk_id_servicio, fk_id_lista_precio));
CREATE TABLE tci03_lista_precio (id_lista_precio SERIAL NOT NULL, fk_id_estado int4 NOT NULL, tx_nombre varchar(50) NOT NULL, fh_inicio timestamp NOT NULL, fh_fin timestamp, PRIMARY KEY (id_lista_precio));
CREATE TABLE tci05_cita (id_cita SERIAL NOT NULL, fk_id_persona int4 NOT NULL, fk_id_servicio int4 NOT NULL, fk_id_lista_precio int4 NOT NULL, fk_id_sucursal int4 NOT NULL, fk_id_empleado int4 NOT NULL, PRIMARY KEY (id_cita));
ALTER TABLE tca01_persona ADD CONSTRAINT FKtca01_pers852780 FOREIGN KEY (fk_id_genero) REFERENCES cca01_genero (id_genero);
ALTER TABLE tca02_usuario ADD CONSTRAINT FKtca02_usua862702 FOREIGN KEY (id_usuario) REFERENCES tca01_persona (id_persona);
ALTER TABLE tci05_cita ADD CONSTRAINT FKtci05_cita559502 FOREIGN KEY (fk_id_persona) REFERENCES tca01_persona (id_persona);
ALTER TABLE tci02_servicio_lista_precio ADD CONSTRAINT FKtci02_serv131929 FOREIGN KEY (fk_id_servicio) REFERENCES cci01_servicio (id_servicio);
ALTER TABLE tci02_servicio_lista_precio ADD CONSTRAINT FKtci02_serv753638 FOREIGN KEY (fk_id_lista_precio) REFERENCES tci03_lista_precio (id_lista_precio);
ALTER TABLE tci03_lista_precio ADD CONSTRAINT FKtci03_list512910 FOREIGN KEY (fk_id_estado) REFERENCES tci01_estado_lista_precio (id_estado);
ALTER TABLE tci05_cita ADD CONSTRAINT FKtci05_cita165698 FOREIGN KEY (fk_id_servicio, fk_id_lista_precio) REFERENCES tci02_servicio_lista_precio (fk_id_servicio, fk_id_lista_precio);
ALTER TABLE tce02_sucursal ADD CONSTRAINT FKtce02_sucu179423 FOREIGN KEY (fk_id_establecimiento) REFERENCES tce01_establecimiento (id_establecimiento);
ALTER TABLE tce08_horario ADD CONSTRAINT FKtce08_hora383650 FOREIGN KEY (fk_id_sucursal) REFERENCES tce02_sucursal (id_sucursal);
ALTER TABLE tce08_horario ADD CONSTRAINT FKtce08_hora893106 FOREIGN KEY (fk_id_dia) REFERENCES tce04_dia_laboral (id_dia);
ALTER TABLE tci05_cita ADD CONSTRAINT FKtci05_cita70185 FOREIGN KEY (fk_id_sucursal) REFERENCES tce02_sucursal (id_sucursal);
ALTER TABLE tce07_bloque_cita ADD CONSTRAINT FKtce07_bloq429895 FOREIGN KEY (fk_id_sucursal) REFERENCES tce02_sucursal (id_sucursal);
ALTER TABLE tca02_usuario ADD CONSTRAINT FKtca02_usua571784 FOREIGN KEY (fk_id_rol) REFERENCES cca02_rol (id_rol);
ALTER TABLE tce03_empleado ADD CONSTRAINT FKtce03_empl270344 FOREIGN KEY (id_empleado) REFERENCES tca01_persona (id_persona);
ALTER TABLE tce06_empleado_horario ADD CONSTRAINT FKtce06_empl130066 FOREIGN KEY (fk_id_persona) REFERENCES tce03_empleado (id_empleado);
ALTER TABLE tce06_empleado_horario ADD CONSTRAINT FKtce06_empl703363 FOREIGN KEY (fk_id_horario) REFERENCES tce08_horario (id_horario);
ALTER TABLE tce05_dia_descanso ADD CONSTRAINT FKtce05_dia_792374 FOREIGN KEY (fk_id_empleado) REFERENCES tce03_empleado (id_empleado);
ALTER TABLE tce07_bloque_cita ADD CONSTRAINT FKtce07_bloq663954 FOREIGN KEY (fk_id_cita) REFERENCES tci05_cita (id_cita);
ALTER TABLE tci05_cita ADD CONSTRAINT FKtci05_cita867560 FOREIGN KEY (fk_id_empleado) REFERENCES tce03_empleado (id_empleado);
ALTER TABLE tce03_empleado ADD CONSTRAINT FKtce03_empl771275 FOREIGN KEY (fk_id_sucursal) REFERENCES tce02_sucursal (id_sucursal);
